# Generated by Django 3.0.7 on 2020-10-10 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabangOlahraga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_olahraga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KelasPertandingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=200)),
                ('batasan_jenis_kelamin', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True)),
                ('batasan_usia_minimal', models.IntegerField(blank=True, null=True)),
                ('batasan_usia_maksimal', models.IntegerField(blank=True, null=True)),
                ('batasan_berat_minimal', models.IntegerField(blank=True, null=True)),
                ('batasan_berat_maksimal', models.IntegerField(blank=True, null=True)),
                ('cabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CabangOlahraga')),
            ],
        ),
        migrations.CreateModel(
            name='Pertandingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pertandingan', models.CharField(max_length=200)),
                ('cabor', models.ManyToManyField(to='main_app.CabangOlahraga')),
                ('kelas', models.ManyToManyField(to='main_app.KelasPertandingan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nama_panggilan', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('jenis_id', models.CharField(blank=True, choices=[('KTP', 'Ktp'), ('KIA', 'Kia'), ('SIM', 'Sim'), ('Paspor', 'Paspor')], max_length=10, null=True)),
                ('nomor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat ID')),
                ('kota_kabupaten_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kota/ Kab.')),
                ('provinsi_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provinsi')),
                ('alamat_tinggal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat Tinggal')),
                ('kota_kabupaten_tinggal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kota/ Kab.')),
                ('provinsi_tinggal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provinsi')),
                ('nomor_ponsel', models.CharField(blank=True, max_length=20, null=True)),
                ('akun_fb', models.CharField(blank=True, max_length=100, null=True)),
                ('akun_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('akun_ig', models.CharField(blank=True, max_length=100, null=True)),
                ('akun_youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PesertaPertandingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.KelasPertandingan')),
                ('pertandingan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pertandingan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
