# Generated by Django 3.0.7 on 2020-10-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabangolahraga',
            options={'ordering': ['nama_olahraga'], 'verbose_name_plural': 'Cabang Olahraga'},
        ),
        migrations.AlterModelOptions(
            name='kelaspertandingan',
            options={'ordering': ['nama_kelas'], 'verbose_name_plural': 'Kelas Pertandingan'},
        ),
        migrations.AlterModelOptions(
            name='pertandingan',
            options={'ordering': ['nama_pertandingan'], 'verbose_name_plural': 'Pertandingan'},
        ),
        migrations.AlterModelOptions(
            name='pesertapertandingan',
            options={'ordering': ['peserta'], 'verbose_name_plural': 'Peserta'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['nama_lengkap']},
        ),
        migrations.AlterField(
            model_name='pesertapertandingan',
            name='peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile'),
        ),
    ]
