# Generated by Django 3.0.7 on 2020-10-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201010_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaborFavorit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabor', models.ManyToManyField(to='main_app.CabangOlahraga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile')),
            ],
        ),
    ]
