# Generated by Django 3.0.7 on 2020-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_caborfavorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cabor_favorit',
            field=models.ManyToManyField(to='main_app.CabangOlahraga'),
        ),
        migrations.DeleteModel(
            name='CaborFavorit',
        ),
    ]
